# GitHub
# baseurl:          /RimeOfficial

# Custom
theme_color:      DA2E75

# Where things are Advanced
paginate: 5
paginate_path: "/posts/page:num/"
sass:
  style: compact # possible values: nested expanded compact compressed
  sass_dir: _sass

collections:
  pages:
    output:       true
    permalink:    /:path
  newsletters:
    output:       true
    permalink:    /newsletters/:path

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-paginate 
  - jekyll-redirect-from
  - jekyll-coffeescript

# Outputting
# permalink:        /:categories/:title
defaults:
  - scope:
      path:       ''
      type:       pages
    values:
      layout:     default

# jekyll-sitemap
defaults:
  - scope:
      path:            "/assets/*"
    values:
      sitemap:         false
      
# jekyll-seo-tag
title:            Rime
tagline:          'Build Business with AI Powered Blog'
description:      'Introducing Arya, your personal blog manager.
  Business Focused - A weblog which connects your different content stream and bring (sync) all your posts in one place. Currently Rime support 11 services.
  Saves time - Our platform organizes your posts into collection and topics. Rime optimizes your weblog for search engines with updated standards. SEO includes meta tags, schema and AMP.
  Builds audience - Host the weblog on your custom domain which defines you completely. From top stories to latest posts, life events to places, everything in one place.'
image:
  path:           /assets/images/logo-share.png
  height:         500
  width:          500
author:           Rhyme Technologies
lang: en_UK
twitter:
  username:       RhymeTek_
  card:           summary
facebook:
  app_id:         510262139040639
  publisher:      297545803726080
  admins:         suvozit
logo:             /assets/images/logo-share.png
social:
  name: Rime
  links:
    - https://twitter.com/RhymeTek_
    - https://www.facebook.com/RimeSocial
    - https://www.linkedin.com/company/rhyme-tek/
    - https://github.com/RimeOfficial
    - https://keybase.io/RhymeTek
    - https://dribbble.com/rimeofficial
    - https://medium.com/rimeofficial
    - https://rimeofficial.tumblr.com
webmaster_verifications:
  google: KT5gs8h0wvaagLKAVWq8bbeNwnZZK1r1XQysX3xurLU

bing-maps: AnWLEJTvYM0b-v3uXLMD4VckmHWGnxj20lIOsT73gvR8akZhXibwFg-6kK4Ek
google-analytics: UA-41643154-1