- name: Avatar
  url: /settings/avatar

- name: Username
  url: /settings/username

- name: Account
  url: /settings/account

- name: Email
  url: /settings/email

- name: Notifications
  url: /settings/notifications

- name: Membership
  url: /settings/membership

- name: Download
  url: /settings/download

- name: Deactivate
  url: /settings/deactivate