- title: About
  url: /about
- title: Jobs
  url: /jobs
- title: FAQ
  url: /support/faq

- title: Blog
  url: https://medium.com/rimeofficial
  attr: target="_blank"
- title: Open Source
  url: http://github.com/RimeOfficial
  attr: target="_blank"
- title: Press
  url: /press

- title: Terms
  url: /legal/terms
- title: Privacy
  url: /legal/privacy
- title: Security
  url: /support/security
- title: Libraries
  url: /support/libraries
- title: Feedback
  url: https://docs.google.com/forms/d/15T8c86v5_QmD887jpHBNLB4teRxHfM_0479QDb_pkV8
  attr: target="_blank"
# - title: Feedback
#   url: mailto:feedback@rime.co